🔀 :: (#120) 학생 세부 정보 조회
EntryDSM/Yapaghetti pull request #122
Opened 2022-07-08 07:42 UTC by osangu

close #120

2022-07-08 14:44 UTC, eogus2513 commented on yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagRepository.java
> +    Optional<TagEntity> findByIdAndType(UUID id, TagType type);
이거 정렬 할꺼면 위에꺼도 같이하면 좋을 거 같아요

2022-07-08 14:44 UTC, eogus2513 commented on yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
> +                .antMatchers(HttpMethod.GET, "/documents//stay/{document-id}").hasAnyRole(STUDENT, TEACHER)
여기 /가 두개 붙어 있어요...

2022-07-09 02:22 UTC, syxxn commented on yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/domain/Student.java
> +	private final UUID tagId; // 학생의 대표 분야 태그에 대한 Id입니다
페메 보시고 majorTagId로 수정 부탁드릴게요

2022-07-09 02:22 UTC, syxxn commented on yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetStudentDetailInformationUseCase.java
> +        Student student = teacherQueryStudentPort.queryUserById(studentId);
이걸 하나씩 다 불러올 게 아니라 querydsl로 join해서 dto로 받아오는 게 좋을 것 같아요. 서준님이 작성한 코드 참고하셔서 수정해주세요

2022-07-09 02:22 UTC, syxxn commented on yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
> +	private TagEntity tagEntity; // 학생의 대표 분야 태그에 대한 Id입니다
주석 없이도 이해할 수 있는 필드명으로 수정하는 게 좋을 것 같아요 다른 분들이랑도 얘기해보고 수정합니다

2022-07-09 03:04 UTC, syxxn requested changes

2022-07-09 03:04 UTC, syxxn commented on yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentDetailInformationResponse.java
> +    private String major;
이건 major tag로 바꾸고

2022-07-09 03:04 UTC, syxxn commented on yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentDetailInformationResponse.java
> +    private List<String> tagNameList;
이건 skillTagList로 바꿉시다

2022-07-09 06:29 UTC, osangu commented
브랜치 새로 파서 위 피드백 수정한 후 다시 PR 올리도록 하겠습니다!

2022-07-09 09:14 UTC, closed without merging