🔀 :: (#5)
EntryDSM/Yapaghetti pull request #19
Opened 2022-06-30 16:30 UTC by syxxn

close #5

2022-06-30 16:35 UTC, leeseojune53 approved these changes

2022-06-30 16:35 UTC, leeseojune53 commented on yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Port.java
> +        String folder = imageType.equals(ImageType.PROFILE) ? awsS3Properties.getProfileFolder() : awsS3Properties.getPreviewFolder();
Extension을 .jped로 하면 강제 코덱 변환때문에 깨질 수 있을거같아요
그리고 jpg, jpeg, png, heic로 늘리는게 좋을것 같습니다

2022-06-30 17:09 UTC, leeseojune53 approved these changes
굿!

2022-06-30 23:23 UTC, eogus2513 approved these changes

2022-06-30 23:36 UTC, softpeanut commented on yapaghetti-infrastructure/build.gradle
> +    //s3
요거 근데 이름이 s3 맞아요?

2022-06-30 23:36 UTC, softpeanut commented on yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Port.java
> +    public void deleteImage(String objectUrl) {
이렇게 되면 이미지를 매번 하나하나 지우게 되는 건가요?

2022-07-01 00:44 UTC, softpeanut approved these changes

2022-07-01 00:47 UTC, leeseojune53 requested changes

2022-07-01 00:47 UTC, leeseojune53 commented on yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Port.java
> +public class AwsS3Port {
Adaptor가 맞는거같아요!

2022-07-01 00:48 UTC, leeseojune53 approved these changes
진짜 굿

2022-07-01 00:50 UTC, merged