🔀 :: (#1) CI 설정
EntryDSM/Yapaghetti pull request #2
Opened 2022-06-23 12:12 UTC by eogus2513

close #1

2022-06-23 12:49 UTC, leeseojune53 requested changes

2022-06-23 13:06 UTC, softpeanut requested changes

2022-06-23 14:00 UTC, eogus2513 commented on .github/workflows/CI.yml
> +name: v1-service-feed - CI
헉... 완전 실수

2022-06-23 23:19 UTC, softpeanut approved these changes

2022-06-24 00:36 UTC, syxxn approved these changes

2022-06-24 07:22 UTC, leeseojune53 approved these changes

2022-06-24 11:47 UTC, merged